[package]
name = "zei"
version = "0.0.1"
authors = ["efe"]
edition = "2018"
description = "Zei: Confidential Payments for Accounts"

[dependencies]
rand = "0.6"
blake2-rfc = "0.2"
curve25519-dalek = { version =  "1.0.0-pre.0", features = ["serde"] }
bulletproofs =  "1.0.0-pre.0"
merlin = "1.0.0-pre.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
index-fixed = "0.3"
schnorr = { git = "https://github.com/stichtingorganism/schnorr" }
organism_utils = { git = "https://github.com/stichtingorganism/utils" }

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "zei_benchmarks"
harness = false

[features]
default = ["std", "u64_backend"]
std = ["curve25519-dalek/std"]
alloc = ["curve25519-dalek/alloc"]
nightly = ["curve25519-dalek/nightly", "rand/nightly"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
avx2_backend = ["curve25519-dalek/avx2_backend"]
