[package]
name = "zei"
version = "0.0.2"
authors = ["fernando@findora.org, philippe@findora.org"]
edition = "2018"
description = "Zei: Findora's Cryptographic Library"

[lib]
name = "zei"
crate-type = ["rlib"]

[dependencies]
boolinator = "2.4.0"
byteorder = { version = "^1.2.3", default-features = false, features = ["i128"] }
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand = { version = "0.7", default-features = false, optional = true }
rand_chacha = "0.2"
num-traits = "0.2"
num-bigint = "0.2.2"
rand_04 = {package= "rand", version = "0.4"}
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
ed25519-dalek = "1.0.0-pre.3"
bulletproofs = { version = "2.0.0",  package = "bulletproofs", git = "https://github.com/dalek-cryptography/bulletproofs", branch = "develop", features = ["yoloproofs"]}
spacesuit = {git = "https://github.com/findoraorg/slingshot", branch = "main"}
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }
merlin = "2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.8.0"
itertools = "0.8.0"
rmp-serde = "0.13.7"
pairing = "0.14.2"
bn = {git = "ssh://git@github.com/findoraorg/zcash-bn-fork", rev = "06d5bd15e358dc5a75b3d0b"}
digest = "0.8"
bincode = "1.1.2"
base64 = "0.10"
linear-map = "1.2.0"
aes-ctr = "0.3.0"

[dev-dependencies]
rand = { version = "0.7", default-features = false}
bit-array = "0.4.3"
typenum = "1.11.2"
criterion = "0.3.1"
criterion-cycles-per-byte = "0.1.1"
zei_utilities = { path = "utilities" }

[features]
default = ["std", "u64_backend"]
std = ["curve25519-dalek/std"]
alloc = ["curve25519-dalek/alloc"]
nightly = ["curve25519-dalek/nightly", "rand/nightly"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
avx2_backend = ["curve25519-dalek/avx2_backend"]

[[bench]]
name = "xfr_note_time"
harness = false

[[bench]]
name = "xfr_note_cycles"
harness = false

[[bench]]
name = "xfr_body_time"
harness = false

[[bench]]
name = "xfr_body_cycles"
harness = false


