[package]
name = "zei"
version = "0.0.1"
authors = ["efe"]
edition = "2018"

[dependencies]
rand = "0.5"
blake2-rfc = "0.2"
curve25519-dalek = { version =  "1.0.0-pre.0", features = ["serde"] }
bulletproofs =  "1.0.0-pre.0"
merlin = "1.0.0-pre.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
index-fixed = "0.3"
schnorr = "0.0.3"