[package]
name = "zei"
version = "0.0.1"
authors = ["efe"]
edition = "2018"
description = "Zei: Confidential Payments for Accounts"

[lib]
name = "zei"
crate-type = ["rlib"]

[dependencies]
rand_chacha = "0.1.1"
num-traits = "0.2"
num-bigint = "0.2.2"
rand = "0.6"
curve25519-dalek = { version =  "1.0", features = ["serde"] }
ed25519-dalek = "0.9.1"
bulletproofs =  "1.0"
merlin = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sodiumoxide = "0.2.0"
blake2 = "0.8.0"
hex = "0.3.2"
bn = {path = "/home/fernando/eian/tmp/pairing/bn"}
rustc-serialize = "0.3"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "zei_benchmarks"
harness = false

[features]
default = ["std", "u64_backend"]
std = ["curve25519-dalek/std"]
alloc = ["curve25519-dalek/alloc"]
nightly = ["curve25519-dalek/nightly", "rand/nightly"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
avx2_backend = ["curve25519-dalek/avx2_backend"]
