[package]
name = "zei"
version = "0.0.3"
authors = ["fernando@findora.org, philippe@findora.org"]
edition = "2018"
description = "Zei: Findora's Cryptographic Library"

[lib]
name = "zei"
crate-type = ["rlib"]

[dependencies]
boolinator = "2.4.0"
byteorder = { version = "^1.2.3", default-features = false, features = ["i128"] }
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand = { version = "0.7", default-features = false, optional = true }
rand_chacha = "0.2"
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
ed25519-dalek = "1.0.0-pre.3"
bulletproofs = { package = "bulletproofs", git = "ssh://git@github.com/findoraorg/bulletproofs", branch = "batch_verification", features = ["yoloproofs"] }
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }
merlin = "2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.8.0"
itertools = "0.8.0"
rmp-serde = "0.13.7"
group = "0.6.0"
ff = "0.6.0"
pairing = "0.16.0"
digest = "0.8"
bincode = "1.1.2"
base64 = "0.10"
linear-map = "1.2.0"
aes-ctr = "0.3.0"
lazy_static = "1.4.0"
x25519-dalek = "0.6"

[dev-dependencies]
rand = { version = "0.7", default-features = false}
bit-array = "0.4.3"
typenum = "1.11.2"
criterion = "0.3.1"
criterion-cycles-per-byte = "0.1.1"
zei_utilities = { path = "utilities" }

[features]
default = ["std", "u64_backend"]
std = ["curve25519-dalek/std"]
alloc = ["curve25519-dalek/alloc"]
nightly = ["curve25519-dalek/nightly", "rand/nightly"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
avx2_backend = ["curve25519-dalek/avx2_backend"]

[[bench]]
name = "xfr_note_idtracking_assettracking_singleasset_time"
harness = false

[[bench]]
name = "xfr_note_idtracking_assettracking_singleasset_cycles"
harness = false

[[bench]]
name = "xfr_note_idtracking_assettracking_multiasset_time"
harness = false

[[bench]]
name = "xfr_note_idtracking_assettracking_multiasset_cycles"
harness = false

[[bench]]
name = "xfr_note_noidtracking_noassettracking_singleasset_time"
harness = false

[[bench]]
name = "xfr_note_noidtracking_noassettracking_singleasset_cycles"
harness = false

[[bench]]
name = "xfr_body_idtracking_assettracking_singleasset_time"
harness = false

[[bench]]
name = "xfr_body_idtracking_assettracking_singleasset_cycles"
harness = false

[[bench]]
name = "xfr_note_batch_cycles"
harness = false

[[bench]]
name = "xfr_note_batch_time"
harness = false

[[bench]]
name = "xfr_note_idtracking_noassettracking_singleasset_time"
harness = false

[[bench]]
name = "xfr_note_idtracking_noassettracking_singleasset_cycles"
harness = false



