[workspace]
members = [
 "accumulators",
 "algebra",
 "crypto",
 "plonk",
 "api",
]
resolver = "2"

[patch.crates-io]
ark-ec = { git = "https://github.com/FindoraNetwork/ark-algebra", branch = "develop-refactoring" }
ark-ff = { git = "https://github.com/FindoraNetwork/ark-algebra", branch = "develop-refactoring" }
ark-serialize = { git = "https://github.com/FindoraNetwork/ark-algebra", branch = "develop-refactoring" }
ark-std = { git = "https://github.com/FindoraNetwork/ark-std", branch = "develop-refactoring" }
ark-bls12-381 = { git = "https://github.com/FindoraNetwork/ark-curves", branch = "develop-refactoring" }
ark-ed-on-bls12-381 = { git = "https://github.com/FindoraNetwork/ark-curves", branch = "develop-refactoring" }
curve25519-dalek = { git = "https://github.com/FindoraNetwork/curve25519-dalek", branch = "develop-refactoring" }
ed25519-dalek = { git = "https://github.com/FindoraNetwork/ed25519-dalek", branch = "develop-refactoring" }
x25519-dalek = { git = "https://github.com/FindoraNetwork/x25519-dalek", branch = "develop-refactoring" }

[profile.release]
opt-level = 3
lto = "thin"
incremental = true
panic = 'abort'

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 3
lto = "thin"
incremental = true
debug-assertions = true
debug = true
panic = 'abort'

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug-assertions = true
debug = true