[package]
name = 'zei-plonk'
version = '0.1.5'
authors = ['Findora <engineering@findora.org>']
edition = '2021'
description = 'Zei TurboPLONK protocol'

[lib]
name = 'zei_plonk'
crate-type = ['rlib']

[dependencies]
bincode = '1.3.1'
custom_error = '1.7.1'
itertools = '0.10.0'
merlin = '3.0.0'
num-bigint = '0.4'
num-integer = '0.1.43'
num-traits = '0.2.12'
rand = '0.8'
rand_chacha = '0.3'
rand_core = '0.6'
ruc = '1.0'
serde_derive = '1.0.115'

[dependencies.zei-algebra]
path = '../algebra'

[dependencies.zei-crypto]
path = '../crypto'

[dependencies.byteorder]
version = '1.2.3'
default-features = false
features = ['i128']

[dependencies.serde]
version = '1.0.115'
features = ['derive']

[dev-dependencies]
serde_json = '1.0'

[dev-dependencies.num-bigint]
version = '0.4'
features = ['rand']
