[package]
name = "algebra"
version = "0.1.0"
authors = ["fernando@findora.org, philippe@findora.org"]
edition = "2018"
description = "Zei Algebra commons"

[lib]
name = "algebra"
crate-type = ["rlib"]

[dependencies]
utils = {path = "../utils" }
byteorder = { version = "^1.2.3", default-features = false, features = ["i128"] }
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand = { version = "0.7", default-features = false, optional = true }
rand_chacha = "0.2"
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
ed25519-dalek = "1.0.0-pre.3"
serde = "1.0"
sha2 = "0.8.0"
group = "0.6.0"
ff = "0.6.0"
pairing = "0.16.0"
digest = "0.8"
jubjub = "0.3.0"

[features]
default = ["std", "u64_backend"]
std = ["curve25519-dalek/std"]
alloc = ["curve25519-dalek/alloc"]
nightly = ["curve25519-dalek/nightly", "rand/nightly"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
avx2_backend = ["curve25519-dalek/avx2_backend"]
