[package]
name = "crypto"
version = "0.1.0"
authors = ["fernando@findora.org, philippe@findora.org"]
edition = "2018"
description = "Zei Cryptographic Primitives and Protocols"

[lib]
name = "crypto"
crate-type = ["rlib"]

[dependencies]
aes-ctr = "0.3.0"
algebra = {path = "../algebra" }
bulletproofs = { package = "bulletproofs", git = "ssh://git@github.com/findoraorg/bulletproofs", branch = "batch_verification", features = ["yoloproofs"] }
byteorder = { version = "^1.2.3", default-features = false, features = ["i128"] }
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
digest = "0.8"
ed25519-dalek = "1.0.0-pre.3"
ff = "0.6.0"
group = "0.6.0"
itertools = "0.8.0"
jubjub = "0.3.0"
linear-map = "1.2.0"
merlin = "2.0"
pairing = "0.16.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand = { version = "0.7", default-features = false }
rand_chacha = "0.2"
serde = "1.0"
serde_derive = "1.0"
sha2 = "0.8.0"
utils = {path = "../utils" }
x25519-dalek = "0.6"

[dev-dependencies]
bit-array = "0.4.3"
lazy_static = "1.4.0"
rmp-serde = "0.13.7"
serde_json = "1.0"
typenum = "1.11.2"



[features]
default = ["std", "u64_backend"]
std = ["curve25519-dalek/std"]
alloc = ["curve25519-dalek/alloc"]
nightly = ["curve25519-dalek/nightly", "rand/nightly"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
avx2_backend = ["curve25519-dalek/avx2_backend"]
